### ISSUE TITLE
Build with --prod and --aot does not work

### ISSUE THREAD

**Issue by iamsvenh** [Adrael/ngx-tweet#1]
**Describe the bug**
When I start a build with the --prod --aot flags, it will fail with the following error: 

ERROR in : Unexpected value 'TweetModule in /node_modules/ngx-tweet/lib/ngx-tweet.module.d.ts' imported by the module 'MyModule in /myApp/app.module.ts'. Please add a @NgModule annotation.

**To Reproduce**

ng build --prod --aot

**Comment by adrael** [comment]
Hi @Badmonky!
I am glad to announce that the [2.0.0](https://github.com/Adrael/ngx-tweet/commit/1475e7ded28613f8a9b5b8633351e5da02df0934) is out!

One of the new things is your bug fix.

Enjoy, and happy tweeting!

**Comment by iamsvenh** [comment]
thank you. will upgrade to V2
