### ISSUE TITLE
Incompatibility with Angular 5?

### ISSUE THREAD

**Issue by zainlateef** [Adrael/ngx-tweet#2]
Hey, this seems like a fantastically convenient library, but I can't seem to get it running out of the box. I've installed several libraries before and after the failed installation of ngx-tweet so my environment seems fine. I've followed the relatively standard installation steps, but I'm receiving this error after importing the library and doing nothing else:
![image](https://user-images.githubusercontent.com/26233794/49163211-69b78b80-f2e1-11e8-9a94-3bc2d44a7233.png)
I'm running Angular 5 on a Mac with Angular CLI 1.7.4
Thank you for your time!

**Comment by rms-bc** [comment]
Hello @zainlateef and thanks for using this lib!

I will investigate this bug ASAP, but just so you know, it is compatible with Angular 6.
I'm going to check if this is an issue breaking backward compatibility.

Will keep you posted!

**Comment by rms-bc** [comment]
@zainlateef , indeed the lib is not backward compatible with Angular 5.
It's been packaged for Angular 6.
Unfortunately, I don't have the time to add support for multiple versions, as I forked and updated this lib according to my own need.

If you feel comfortable to upgrade your app to Angular 6 (even 7 now), I strongly recommend that you do so.
If not, it may be worth your while to fork this repo and make it compatible with Angular 5.

Anyway, thanks for your time!
